# Generated by Django 2.2.2 on 2020-04-01 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_auto_20200331_2353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceInfo',
        ),
    ]
