# Generated by Django 3.0.6 on 2020-07-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_delete_invoiceinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
