# Generated by Django 3.0.6 on 2020-08-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_auto_20200731_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.TextField(blank=True),
        ),
    ]
