# Generated by Django 2.2.2 on 2020-04-03 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_inspector_app', '0002_auto_20200403_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceinfo',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 3, 23, 21, 48, 17277)),
        ),
        migrations.AddField(
            model_name='invoiceinfo',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
