# Generated by Django 2.2.2 on 2020-04-03 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_inspector_app', '0004_auto_20200403_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceinfo',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 3, 23, 22, 42, 945343)),
        ),
    ]
