# Generated by Django 2.2.2 on 2020-04-03 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_inspector_app', '0006_auto_20200403_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceinfo',
            options={},
        ),
        migrations.RemoveField(
            model_name='invoiceinfo',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='invoiceinfo',
            name='status',
        ),
    ]
