# Generated by Django 2.2.2 on 2020-05-07 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_inspector_app', '0007_auto_20200403_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
