# Generated by Django 2.2.2 on 2020-05-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_inspector_app', '0010_invoicecollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecollection',
            name='name',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
