# Generated by Django 3.0.6 on 2020-08-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_inspector_app', '0011_invoicecollection_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecollection',
            name='company',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
