# Generated by Django 3.0.6 on 2020-08-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_inspector_app', '0012_invoicecollection_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceinfo',
            name='name',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
