# Generated by Django 3.0.6 on 2020-10-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_inspector_app', '0013_invoiceinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecollection',
            name='fileName',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
